fix Python 3 incompatability
Fixes:

  File "cell.py", line 3, in <module>
    import mpio
  File "/usr/lib/python3.5/site-packages/mpio/__init__.py", line 27, in <module>
    from .input import Input
  File "/usr/lib/python3.5/site-packages/mpio/input.py", line 33, in <module>
    _EVIOCGNAME = IOC(IOC_READ, 69, 0x06, 255)
  File "/usr/lib/python3.5/site-packages/mpio/ioctl.py", line 54, in IOC
    if isinstance(size, str) or isinstance(size, unicode):
  NameError: name 'unicode' is not defined

In Python 3 every string is a unicode type, so the check causing the problem is
only necessary for Python 2.

Signed-off-by: Joshua Henderson <joshua.henderson@microchip.com>