mpio: fix close() on uninitialized objects
If an object is not properly initialized, close() will be called and an attempt
to use undefined attributes will happen generating an error like:

>>> g = mpio.GPIO(107)
Exception AttributeError: "'GPIO' object has no attribute '_fd'" in <bound method GPIO.__del__ of <mpio.gpio_cdev.GPIO object at 0xb6b22c50>> ignored
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: __init__() takes at least 3 arguments (2 given)

To prevent this from happening, check to make sure attributes required by
close() are defined.

Signed-off-by: Joshua Henderson <joshua.henderson@microchip.com>